name: iOS Build

on:
  push:
    branches:
      - 'epic/**'
  pull_request:
    branches:
      - 'epic/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.0'

    - name: Install CocoaPods (if Podfile exists)
      run: |
        if [ -f Podfile ]; then
          gem install cocoapods
          pod install --repo-update
        fi

    - name: Build the SDK
      run: swift build --configuration release

    - name: Run Unit Tests
      run: swift test --configuration release

    - name: Lint code
      run: |
        gem install swiftlint
        swiftlint

    - name: Build for iOS
      run: |
        xcodebuild -scheme YourSchemeName \
        -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
        clean build \
        CODE_SIGN_IDENTITY="" \
        CODE_SIGNING_REQUIRED=NO
